---
- name: "Ensure SELinux is disabled on all hosts"
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: "Ensure SELinux is disabled"
      ansible.builtin.selinux:
        state: disabled
