---
- name: "Ansible Playbook to install a Zookeeper ensemble and Kafka Broker Authenticated"
  hosts: brokers
  vars_files:
    - vars.yml
  vars:
    amq_streams_broker_sysctl_vm_max_map_count: 165530
    amq_streams_broker_ulimit_max_value: 10240

    amq_streams_broker_listeners:
      - AUTHENTICATED://:{{ amq_streams_broker_listener_port }} # Authenticated
      - REPLICATION://:{{ amq_streams_broker_listener_internal_port }} # Inter broker communication

    amq_streams_broker_inter_broker_listener: REPLICATION

    amq_streams_broker_auth_enabled: true
    amq_streams_broker_auth_scram_enabled: true
    amq_streams_broker_auth_listeners:
      - AUTHENTICATED:SASL_PLAINTEXT
      - REPLICATION:SASL_PLAINTEXT

    amq_streams_broker_auth_sasl_mechanisms:
      - PLAIN
      - SCRAM-SHA-512

    # Kafka Plain Users
    amq_streams_broker_auth_plain_users:
      - username: admin
        password: "{{ amq_streams_zookeeper_auth_pass }}"
      - username: kafkauser
        password: "{{ amq_streams_zookeeper_auth_pass }}"

    amq_streams_broker_inter_broker_auth_sasl_mechanisms: PLAIN
    amq_streams_broker_inter_broker_auth_broker_username: interbroker
    amq_streams_broker_inter_broker_auth_broker_password: "{{ amq_streams_zookeeper_auth_pass }}"
    amq_streams_broker_offsets_topic_replication_factor: 3
    amq_streams_broker_transaction_state_log_replication_factor: 3
    amq_streams_broker_transaction_state_log_min_isr: 2
    # use all zk available in the zookeepers group
    amq_streams_zookeeper_inventory_group: "{{ groups['zookeepers'] }}"
    amq_streams_broker_properties_template: templates/server.properties.j2
  collections:
     - middleware_automation.amq_streams
  pre_tasks:
     - name: "Ensure zookeepers password has been provided."
       ansible.builtin.assert:
         that:
           - amq_streams_zookeeper_auth_pass is defined
           - amq_streams_zookeeper_auth_pass | length > 0
         quiet: true

     - name: "Print all members of the zookeepers ensemble."
       ansible.builtin.debug:
         var: amq_streams_zookeeper_inventory_group
  tasks:
    - ansible.builtin.include_role:
        name: amq_streams_broker
  post_tasks:
    - name: "Display numbers of broker instances managed by Ansible."
      ansible.builtin.debug:
        msg: "Numbers of broker instances: {{ amq_streams_broker_instance_count }}."
      when:
        - amq_streams_broker_instance_count_enabled is defined and amq_streams_broker_instance_count_enabled

    - name: "Validate that Broker deployment is functional."
      ansible.builtin.include_role:
        name: amq_streams_broker
        tasks_from: validate.yml
