---
- name: "Ansible Playbook to deploy Cruise Control"
  hosts: cruise_controllers
  gather_facts: False
  become: yes
  vars:
    amq_streams_common_offline_install: False
    amq_streams_common_version: 2.5.1
    # only to speed playbook execution after first run:
    #amq_streams_common_skip_deps: True
    amq_streams_common_archive_file: amq-streams-2.5.1-cruise-control-bin.zip
    amq_stream_cruise_control_home: /opt/cruise-control/
    amq_stream_common_home: /opt/kafka_2.13-3.5.0.redhat-00014/
    amq_streams_common_subdir: cruise-control
    # note that the following value is string, not a Ansible bool
    amq_streams_cruise_control_dry_mode: 'true'
    # add security requirement
    amq_streams_cruise_control_zk_security_protocol: SASL_PLAINTEXT
    amq_streams_cruise_control_zk_sasl_mechanism: PLAIN
    # cluster information
    #amq_streams_cruise_control_broker_host:	ip-172-31-17-73.us-east-2.compute.internal
    #amq_streams_cruise_control_zk_host: ip-172-31-22-217.us-east-2.compute.internal
    amq_streams_broker_inventory_group: "{{ groups['brokers'] }}"
    amq_streams_common_redhat_enable: True
    # to cleanup
    amq_streams_zookeeper_auth_enabled: True
    amq_streams_zookeeper_auth_user: zkadmin
    amq_streams_zookeeper_auth_pass: zkpassword
    amq_streams_broker_username: kafkauser
    amq_streams_broker_password: "{{ amq_streams_zookeeper_auth_pass }}"
    amq_streams_broker_admin_username: admin
    amq_streams_broker_admin_password: "{{ amq_streams_zookeeper_auth_pass }}"
    amq_streams_broker_inter_broker_auth_sasl_protocol: SASL_PLAINTEXT
    amq_streams_broker_inter_broker_auth_sasl_mechanisms: PLAIN
    #
  collections:
     - redhat.amq_streams
  roles:
    - role: amq_streams_cruise_control
  pre_tasks:
    - name: "Ensure JAAS config is up to date."
      ansible.builtin.include_tasks: jaas_config.yml

  post_tasks:
    - name: "Use Cruise Control to rebalance the cluster"
      ansible.builtin.include_role:
        name: amq_streams_cruise_control
        tasks_from: cruise_control_operation.yml
      vars:
        operation_name: rebalance
