---
- name: "Displays all groups"
  hosts: all
  gather_facts: no
  tasks:
    - ansible.builtin.debug:
        var: groups

- name: "Ping each host of the inventory"
  hosts: all
  gather_facts: no
  order: reverse_inventory
  serial: 1
  tasks:

   - name: "Ping host (belongs to group {{ groupname }}"
     ansible.builtin.ping:
