---
- name: "Ansible Playbook to install a Zookeeper ensemble with auth"
  hosts: zookeepers
  become: yes
  gather_facts: yes
  vars_files:
    - vars.yml
  vars:
    amq_streams_common_prometheus_enabled: True
    amq_streams_common_prometheus_path_config_file: zookeeper-metrics-config.yaml
    amq_streams_common_prometheus_config_file_template: templates/zookeeper-metrics-config.yaml.j2
  collections:
    - redhat.amq_streams
  roles:
    - role: redhat.amq_streams.amq_streams_zookeeper

  pre_tasks:
    - name: "Ensure ZK admin password has been defined."
      ansible.builtin.assert:
        that:
          - amq_streams_zookeeper_auth_pass is defined and amq_streams_zookeeper_auth_pass | length > 0
        quiet: true

  post_tasks:
    - name: "Display numbers of Zookeeper instances managed by Ansible."
      ansible.builtin.debug:
        msg: "Numbers of Zookeeper instances: {{ amq_streams_zookeeper_instance_count }}."
      when:
        - amq_streams_zookeeper_instance_count_enabled is defined and amq_streams_zookeeper_instance_count_enabled

    - name: "Validate that Zookeeper deployment is functional."
      ansible.builtin.include_role:
        name: redhat.amq_streams.amq_streams_zookeeper
        tasks_from: validate.yml
