---
- name: "Ansible Playbook to install a Zookeeper ensemble with auth"
  hosts: zookeepers
  vars_files:
    - vars.yml
  collections:
    - middleware_automation.amq_streams
  roles:
    - role: middleware_automation.amq_streams.amq_streams_zookeeper

  pre_tasks:
    - ansible.builtin.debug:
        var: groups
    - name: "Ensure ZK admin password has been defined."
      ansible.builtin.assert:
        that:
          - amq_streams_zookeeper_auth_pass is defined and amq_streams_zookeeper_auth_pass | length > 0
        quiet: true
  post_tasks:
    - name: "Display numbers of Zookeeper instances managed by Ansible."
      ansible.builtin.debug:
        msg: "Numbers of Zookeeper instances: {{ amq_streams_zookeeper_instance_count }}."
      when:
        - amq_streams_zookeeper_instance_count_enabled is defined and amq_streams_zookeeper_instance_count_enabled

    - name: "Validate that Zookeeper deployment is functional."
      ansible.builtin.include_role:
        name: middleware_automation.amq_streams_zookeeper
        tasks_from: validate.yml
